/**
 * claude-ai.js
 *
 * Real-Claude implementation of the two *analytical* document tasks that the
 * app uses. It is a drop-in companion to scripts/mock-ai.js:
 *
 *   generateDocuments(interview) -> { [filename]: content }   (async)
 *   analyzeCompany(interviews)   -> markdown string            (async)
 *   isEnabled()                  -> boolean
 *
 * Design:
 *   - The 3 *mechanical* documents (workflow.md / workflow.csv /
 *     workflow-diagram.md) are pure formatting of the interview answers, so we
 *     keep generating them with mock-ai (free, deterministic, identical layout).
 *   - The 3 *analytical* documents (job-description.md / kpi.md /
 *     optimization.md) and the company-wide report are generated by Claude
 *     (model: Sonnet 4.6) because that is where real reasoning adds value.
 *   - Prompt caching is applied to the (stable) system prompts so that running
 *     many employees in a row only pays for the system prompt once.
 *   - Every Claude call is wrapped so that ANY failure (no SDK installed,
 *     missing/invalid key, network error, malformed output) silently falls back
 *     to mock-ai. The app must never break because of the AI layer.
 *
 * Output language: Thai only (matches mock-ai).
 *
 * Configuration (env):
 *   ANTHROPIC_API_KEY   required to enable Claude. Absent -> falls back to mock.
 *   CLAUDE_MODEL        optional override (default: claude-sonnet-4-6)
 */

const mock = require('./mock-ai');

const MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';

// ------------------------------------------------------------------
// Lazy SDK / client init — requiring this file must never throw, even
// if @anthropic-ai/sdk isn't installed yet or the key is missing.
// ------------------------------------------------------------------
let _client = null;
let _initTried = false;

function getClient() {
  if (_client) return _client;
  if (_initTried) return null; // already failed once — don't retry require on every call
  _initTried = true;
  try {
    const sdk = require('@anthropic-ai/sdk');
    const Anthropic = sdk.Anthropic || sdk.default || sdk;
    _client = new Anthropic(); // reads ANTHROPIC_API_KEY from env
    return _client;
  } catch (e) {
    console.error('[claude-ai] SDK not available — using mock-ai. (' + e.message + ')');
    return null;
  }
}

function isEnabled() {
  return !!process.env.ANTHROPIC_API_KEY;
}

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------
const pad = (n) => String(n).padStart(2, '0');

function getAnswer(interview, key) {
  const a = (interview.answers || []).find((x) => x.key === key);
  return a ? a.value : '';
}

function trunc(s, n) {
  const str = String(s || '').trim();
  return str.length > n ? str.slice(0, n) + '…' : str;
}

// Today in YYYY-MM-DD (Christian Era), from the server clock — passed into the
// prompts so Claude never has to guess/hallucinate the document date.
function todayStr() {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

// Run a Claude message and return the concatenated text of the response.
// Uses streaming + finalMessage() so long outputs never hit a request timeout.
async function runClaude({ system, user, maxTokens = 8000 }) {
  const client = getClient();
  if (!client) throw new Error('claude client unavailable');

  const stream = client.messages.stream({
    model: MODEL,
    max_tokens: maxTokens,
    thinking: { type: 'adaptive' },
    output_config: { effort: 'medium' },
    system: [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }],
    messages: [{ role: 'user', content: user }],
  });

  const msg = await stream.finalMessage();

  if (msg.stop_reason === 'refusal') {
    throw new Error('claude refused the request');
  }

  const text = (msg.content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();

  if (!text) throw new Error('claude returned empty text');
  return text;
}

// ------------------------------------------------------------------
// Build the per-employee context block from the interview answers
// ------------------------------------------------------------------
function buildEmployeeContext(interview) {
  const e = interview.employee || {};
  const lines = [];
  lines.push(`วันที่จัดทำ (ใช้วันที่นี้เท่านั้น): ${todayStr()}`);
  lines.push('');
  lines.push('ข้อมูลพนักงาน:');
  lines.push(`- ชื่อ: ${e.name || '-'}`);
  lines.push(`- ตำแหน่ง: ${e.role || '-'}`);
  lines.push(`- ฝ่าย/แผนก: ${e.department || e.division_name || e.division_id || '-'}`);
  lines.push(`- ภาษาที่ใช้สัมภาษณ์: ${String(interview.lang || 'th').toUpperCase()}`);
  lines.push('');
  lines.push(`บทบาทโดยสรุป (จากคำตอบ): ${getAnswer(interview, 'warmup') || '(ไม่ระบุ)'}`);
  lines.push('');

  // Time content — prefer the new hourly schema, fall back to the legacy schema.
  const hourLines = [];
  for (let h = 0; h < 24; h++) {
    const v = getAnswer(interview, `hour_${h}`);
    if (v) hourLines.push(`- ${pad(h)}:00–${pad(h + 1)}:00 → ${v}`);
  }
  if (hourLines.length) {
    lines.push('ตารางงานรายชั่วโมง:');
    lines.push(...hourLines);
  } else {
    const legacy = [
      ['morning_first', '30 นาทีแรกของวัน'],
      ['morning_main', 'งานหลักช่วงสาย (09:30–12:00)'],
      ['morning_tools', 'เครื่องมือ/ระบบช่วงเช้า'],
      ['morning_people', 'ประสานงานช่วงเช้ากับ'],
      ['noon_break', 'พักเที่ยง'],
      ['afternoon_main', 'งานบ่าย (13:00–16:00)'],
      ['afternoon_reports', 'รายงานประจำวัน'],
      ['afternoon_deadline', 'Deadline รายวัน'],
      ['evening_closing', 'ก่อนเลิกงาน'],
    ];
    const legacyLines = legacy
      .map(([k, label]) => {
        const v = getAnswer(interview, k);
        return v ? `- ${label}: ${v}` : null;
      })
      .filter(Boolean);
    if (legacyLines.length) {
      lines.push('ตารางงานประจำวัน:');
      lines.push(...legacyLines);
    }
  }
  lines.push('');

  const tail = [
    ['weekly_tasks', 'งานรายสัปดาห์/รายเดือน'],
    ['pain_points', 'งานที่เสียเวลา/น่าเบื่อ/ทำซ้ำที่สุด'],
    ['bottlenecks', 'คอขวด — รออะไรจากคน/ระบบอื่น'],
    ['own_kpi', 'ตัวชี้วัดในมุมพนักงานเอง'],
    ['ai_wishlist', 'งานที่พนักงานอยากให้ AI ช่วย'],
  ];
  for (const [k, label] of tail) {
    const v = getAnswer(interview, k);
    if (v) lines.push(`${label}: ${v}`);
  }

  const divAns = (interview.answers || []).filter((a) => a.key.startsWith('div_'));
  if (divAns.length) {
    lines.push('');
    lines.push('ข้อมูลเฉพาะฝ่าย:');
    for (const a of divAns) lines.push(`- ${a.value}`);
  }

  if (interview.worklogSummary) {
    lines.push('');
    lines.push('— ข้อมูลจากบันทึกงานประจำวันจริง (สำคัญ: ใช้ประกอบการวิเคราะห์ โดยเฉพาะ KPI และ Optimization — งานที่ทำซ้ำบ่อยคือเป้าหมายการลดงาน/ใช้ AI) —');
    lines.push(interview.worklogSummary);
  }

  return lines.join('\n');
}

// ------------------------------------------------------------------
// 1) Per-employee analytical documents (JD / KPI / Optimization)
// ------------------------------------------------------------------
const SYS_DOCS = `คุณเป็นผู้เชี่ยวชาญด้านทรัพยากรบุคคล (HR) และที่ปรึกษาการจัดการองค์กรที่มีประสบการณ์สูง สำหรับองค์กรในประเทศไทย

หน้าที่: อ่าน "ข้อมูลการสัมภาษณ์การทำงานประจำวัน" ของพนักงาน 1 คน แล้วจัดทำเอกสาร 3 ฉบับเป็นภาษาไทย รูปแบบ Markdown ได้แก่
(1) Job Description — ใบกำหนดหน้าที่งานที่อิงจากงานจริงที่พนักงานทำ
(2) KPI — ตัวชี้วัดผลงานที่วัดได้จริง สอดคล้องกับหน้าที่
(3) Optimization — ข้อเสนอปรับปรุง workflow และการนำ AI/automation มาช่วย

กฎสำคัญ:
- ใช้เฉพาะข้อเท็จจริงที่ปรากฏในข้อมูลสัมภาษณ์เท่านั้น ห้ามแต่งตัวเลข ชื่อระบบ หรือรายละเอียดที่ไม่มีในข้อมูล หากข้อมูลไม่พอในหัวข้อใด ให้เขียนว่า "(ข้อมูลไม่เพียงพอ — ควรสอบถามเพิ่ม)"
- เขียนให้เป็นรูปธรรม อ้างถึงงาน/เครื่องมือ/ช่วงเวลาจริงที่พนักงานบอก ไม่ใช้คำกว้าง ๆ ลอย ๆ
- ภาษากระชับ มืออาชีพ เหมาะนำเสนอผู้บริหาร
- หากต้องระบุวันที่ ให้ใช้ "วันที่จัดทำ" ที่ให้ไว้ในข้อมูลเท่านั้น (รูปแบบ ค.ศ.) ห้ามเดาหรือแต่งวันที่เอง
- ห้ามใส่ข้อความนำ/ทักทาย/สรุปนอกเหนือจากเนื้อหาเอกสาร และห้ามครอบด้วย code fence

โครงสร้างของแต่ละเอกสาร:

[Job Description]
- ขึ้นต้นด้วย "# Job Description: <ชื่อพนักงาน>"
- ## ตำแหน่ง (พร้อมแผนก/ฝ่าย)
- ## สรุปบทบาท (Role Summary) 2–3 บรรทัด
- ## หน้าที่หลัก (Primary Responsibilities) — bullet
- ## หน้าที่รอง (Secondary Responsibilities) — bullet
- ## เครื่องมือ/ระบบที่ต้องใช้ — bullet
- ## การประสานงาน (ทำงานร่วมกับใคร/ฝ่ายใด) — bullet
- ## คุณสมบัติ/Competency ที่จำเป็น — bullet (สังเกตจากงานจริง)
- ## ตัวชี้วัดที่เกี่ยวข้อง (เชื่อมกับ KPI) — bullet สั้น ๆ

[KPI]
- ขึ้นต้นด้วย "# KPI: <ชื่อพนักงาน> (<ตำแหน่ง>)"
- กำหนด KPI 4–6 ตัว ที่อิงจากงานจริง แต่ละตัวต้องมี: ชื่อ KPI / สิ่งที่วัด / สูตรคำนวณ / เป้าหมาย (ตัวเลขสมเหตุสมผล) / ความถี่ในการวัด / น้ำหนัก (%)
- น้ำหนักรวมทุก KPI = 100%
- ปิดท้ายด้วย ## วิธีนำไปใช้ (Baseline → ตกลงเป้ากับหัวหน้า → ทบทวนรายไตรมาส)

[Optimization]
- ขึ้นต้นด้วย "# Optimization: <ชื่อพนักงาน> (<ตำแหน่ง>)"
- ## ปัญหา/คอขวดที่พบ — สรุปจากข้อมูล
- ## ข้อเสนอการปรับปรุง — แต่ละข้อระบุ: ปัญหา / ข้อเสนอเชิงรูปธรรม (ถ้าใช้ AI ให้เจาะจงว่าใช้กับงานไหน อย่างไร) / ผลกระทบ (impact: สูง/กลาง/ต่ำ) / ความเสี่ยง / ความยากง่ายในการทำ
- ## Quick Wins (ทำได้เร็ว) กับ ## ระยะยาว แยกกัน
- ## ประมาณการเวลาที่ประหยัดได้ (ระบุว่าเป็นการประมาณ ต้อง baseline ก่อนวัดจริง)

รูปแบบผลลัพธ์ — ตอบกลับเป็นข้อความเดียว แบ่งเป็น 3 ส่วนด้วยเครื่องหมายคั่นต่อไปนี้แบบเป๊ะ ๆ (ต้องมีครบทั้ง 3 เครื่องหมาย และห้ามมีข้อความอื่นนอกเหนือจากนี้):
===JOB_DESCRIPTION===
<เนื้อหา Markdown ของ Job Description>
===KPI===
<เนื้อหา Markdown ของ KPI>
===OPTIMIZATION===
<เนื้อหา Markdown ของ Optimization>`;

function splitDocs(text) {
  const re = /===JOB_DESCRIPTION===([\s\S]*?)===KPI===([\s\S]*?)===OPTIMIZATION===([\s\S]*)$/;
  const m = text.match(re);
  if (!m) return null;
  const jd = m[1].trim();
  const kpi = m[2].trim();
  const opt = m[3].trim();
  if (!jd || !kpi || !opt) return null;
  return { jd, kpi, opt };
}

async function generateDocuments(interview) {
  // Always start from the mock output: this gives us the 3 mechanical docs for
  // free AND a complete safe fallback for the 3 analytical docs.
  const docs = mock.generateDocuments(interview);

  if (!isEnabled()) return docs;

  try {
    const text = await runClaude({
      system: SYS_DOCS,
      user: buildEmployeeContext(interview),
      maxTokens: 8000,
    });
    const parsed = splitDocs(text);
    if (parsed) {
      docs['job-description.md'] = parsed.jd;
      docs['kpi.md'] = parsed.kpi;
      docs['optimization.md'] = parsed.opt;
    } else {
      console.error('[claude-ai] could not parse 3-section output — keeping mock JD/KPI/Optimization');
    }
  } catch (e) {
    console.error('[claude-ai] generateDocuments failed — keeping mock JD/KPI/Optimization: ' + e.message);
  }

  return docs;
}

// ------------------------------------------------------------------
// 2) Company-wide analysis report
// ------------------------------------------------------------------
const SYS_COMPANY = `คุณเป็นที่ปรึกษาด้านการจัดการและ Transformation อาวุโส กำลังจัดทำรายงานวิเคราะห์ภาพรวมองค์กรในประเทศไทย จากผลการสัมภาษณ์การทำงานประจำวันของพนักงานหลายคน

หน้าที่: สังเคราะห์ข้อมูลทั้งหมด แล้วเขียนรายงานภาษาไทย รูปแบบ Markdown 1 ฉบับ สำหรับนำเสนอผู้บริหารระดับสูง

กฎสำคัญ:
- วิเคราะห์ข้ามฝ่าย หาธีมปัญหาที่เกิดซ้ำหลายคน/หลายฝ่าย ไม่ใช่แค่ลิสต์รายคน
- อิงจากข้อมูลจริงเท่านั้น ห้ามแต่งตัวเลขหรือข้อเท็จจริงที่ไม่มี
- จัดลำดับความสำคัญของข้อเสนอแบบ impact ปะทะ effort
- ภาษากระชับ ตรงประเด็น เหมาะนำเสนอผู้บริหาร
- ในส่วน "วันที่จัดทำ" ให้ใช้วันที่ที่ระบุไว้ในข้อมูลเท่านั้น (รูปแบบ ค.ศ.) ห้ามเดาหรือแต่งวันที่เอง
- ห้ามครอบผลลัพธ์ด้วย code fence และห้ามมีข้อความนำ/ทักทาย

โครงสร้างรายงาน:
- "# รายงานวิเคราะห์ภาพรวมองค์กร — Optimization"
- ## บทสรุปผู้บริหาร (Executive Summary) 3–5 บรรทัด
- ## ความครอบคลุมรายฝ่าย (จำนวนคนที่สัมภาษณ์ในแต่ละฝ่าย)
- ## ธีมปัญหา/คอขวดที่พบซ้ำ — จัดกลุ่มเป็นหัวข้อ พร้อมระบุว่าพบในฝ่ายใด/กี่คน
- ## โอกาสใช้ AI/Automation — จัดลำดับความสำคัญ (impact สูง→ต่ำ) แต่ละข้อบอกว่าช่วยงานอะไร กระทบใครบ้าง
- ## ข้อเสนอภาพรวม + Roadmap 3–6 เดือน (แบ่ง Quick Wins / ระยะกลาง / ระยะยาว)
- ## ความเสี่ยงและข้อควรระวัง`;

function buildCompanyContext(interviews) {
  const lines = [];
  lines.push(`วันที่จัดทำรายงาน (ใช้วันที่นี้เท่านั้น): ${todayStr()}`);
  lines.push(`จำนวนพนักงานที่สัมภาษณ์เสร็จแล้ว: ${interviews.length} คน`);
  lines.push('');
  interviews.forEach((iv, i) => {
    const e = iv.employee || {};
    lines.push(
      `[${i + 1}] ${e.name || '-'} — ${e.role || '-'} (ฝ่าย: ${e.division_name || e.division_id || '-'})`
    );
    const role = getAnswer(iv, 'warmup');
    if (role) lines.push(`   บทบาท: ${trunc(role, 200)}`);
    const pain = getAnswer(iv, 'pain_points');
    if (pain) lines.push(`   ปัญหา/เสียเวลา: ${trunc(pain, 300)}`);
    const bot = getAnswer(iv, 'bottlenecks');
    if (bot) lines.push(`   คอขวด: ${trunc(bot, 300)}`);
    const wish = getAnswer(iv, 'ai_wishlist');
    if (wish) lines.push(`   อยากให้ AI ช่วย: ${trunc(wish, 300)}`);
    const kpi = getAnswer(iv, 'own_kpi');
    if (kpi) lines.push(`   ตัวชี้วัดในมุมตัวเอง: ${trunc(kpi, 200)}`);
    lines.push('');
  });
  return lines.join('\n');
}

async function analyzeCompany(interviews) {
  const list = interviews || [];
  if (!list.length) return mock.analyzeCompany(list);
  if (!isEnabled()) return mock.analyzeCompany(list);

  try {
    return await runClaude({
      system: SYS_COMPANY,
      user: buildCompanyContext(list),
      maxTokens: 8000,
    });
  } catch (e) {
    console.error('[claude-ai] analyzeCompany failed — using mock report: ' + e.message);
    return mock.analyzeCompany(list);
  }
}

module.exports = {
  isEnabled,
  generateDocuments,
  analyzeCompany,
  // re-export the mock-only helpers so callers can use one module if they want
  getNextQuestion: mock.getNextQuestion,
  shouldProbe: mock.shouldProbe,
  listSchedules: mock.listSchedules,
  buildScript: mock.buildScript,
  SCHEDULES: mock.SCHEDULES,
  DIVISION_QUESTIONS: mock.DIVISION_QUESTIONS,
  questionsForDivision: mock.questionsForDivision,
  MODEL,
};
