/**
 * claude-ai.js
 *
 * Real-Claude implementation of the two *analytical* document tasks that the
 * app uses. It is a drop-in companion to scripts/mock-ai.js:
 *
 *   generateDocuments(interview) -> { [filename]: content }   (async)
 *   analyzeCompany(interviews)   -> markdown string            (async)
 *   isEnabled()                  -> boolean
 *
 * Design:
 *   - The 3 *mechanical* documents (workflow.md / workflow.csv /
 *     workflow-diagram.md) are pure formatting of the interview answers, so we
 *     keep generating them with mock-ai (free, deterministic, identical layout).
 *   - The 3 *analytical* documents (job-description.md / kpi.md /
 *     optimization.md) and the company-wide report are generated by Claude
 *     (model: Sonnet 4.6) because that is where real reasoning adds value.
 *   - Prompt caching is applied to the (stable) system prompts so that running
 *     many employees in a row only pays for the system prompt once.
 *   - Every Claude call is wrapped so that ANY failure (no SDK installed,
 *     missing/invalid key, network error, malformed output) silently falls back
 *     to mock-ai. The app must never break because of the AI layer.
 *
 * Output language: Thai only (matches mock-ai).
 *
 * Configuration (env):
 *   ANTHROPIC_API_KEY   required to enable Claude. Absent -> falls back to mock.
 *   CLAUDE_MODEL        optional override (default: claude-sonnet-4-6)
 */

const mock = require('./mock-ai');

const MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';

// ------------------------------------------------------------------
// Pricing — USD per 1,000,000 tokens, by model. Used only to *estimate*
// the cost shown to admins (Anthropic bills in USD). cache_write is the
// 5-min ephemeral write rate (1.25x base input); cache_read is 0.1x.
// ------------------------------------------------------------------
const PRICING = {
  'claude-sonnet-4-6': { input: 3,  output: 15, cache_write: 3.75, cache_read: 0.30 },
  'claude-opus-4-8':   { input: 5,  output: 25, cache_write: 6.25, cache_read: 0.50 },
  'claude-haiku-4-5':  { input: 1,  output: 5,  cache_write: 1.25, cache_read: 0.10 },
};
// Rough THB conversion for display only (override with env USD_TO_THB).
const USD_TO_THB = Number(process.env.USD_TO_THB) || 36;

function priceFor(model) { return PRICING[model] || PRICING['claude-sonnet-4-6']; }

// Turn a raw Anthropic usage object into a flat record with an estimated cost.
function usageRecord(usage) {
  const p = priceFor(MODEL);
  const input = usage.input_tokens || 0;
  const output = usage.output_tokens || 0;
  const cw = usage.cache_creation_input_tokens || 0;
  const cr = usage.cache_read_input_tokens || 0;
  const usd = (input * p.input + output * p.output + cw * p.cache_write + cr * p.cache_read) / 1e6;
  return { model: MODEL, input, output, cache_write: cw, cache_read: cr, cost_usd: usd, cost_thb: usd * USD_TO_THB };
}

// ------------------------------------------------------------------
// Lazy SDK / client init — requiring this file must never throw, even
// if @anthropic-ai/sdk isn't installed yet or the key is missing.
// ------------------------------------------------------------------
let _client = null;
let _initTried = false;

function getClient() {
  if (_client) return _client;
  if (_initTried) return null; // already failed once — don't retry require on every call
  _initTried = true;
  try {
    const sdk = require('@anthropic-ai/sdk');
    const Anthropic = sdk.Anthropic || sdk.default || sdk;
    _client = new Anthropic(); // reads ANTHROPIC_API_KEY from env
    return _client;
  } catch (e) {
    console.error('[claude-ai] SDK not available — using mock-ai. (' + e.message + ')');
    return null;
  }
}

function isEnabled() {
  return !!process.env.ANTHROPIC_API_KEY;
}

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------
const pad = (n) => String(n).padStart(2, '0');

function getAnswer(interview, key) {
  const a = (interview.answers || []).find((x) => x.key === key);
  return a ? a.value : '';
}

function trunc(s, n) {
  const str = String(s || '').trim();
  return str.length > n ? str.slice(0, n) + '…' : str;
}

// Today in YYYY-MM-DD (Christian Era) anchored to Asia/Bangkok — passed into the
// prompts so Claude never has to guess/hallucinate the document date (and never
// drifts a day when the server runs on UTC).
function todayStr() {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Bangkok', year: 'numeric', month: '2-digit', day: '2-digit',
  }).format(new Date());
}

// Run a Claude message and return the concatenated text of the response.
// Uses streaming + finalMessage() so long outputs never hit a request timeout.
async function runClaude({ system, user, maxTokens = 8000, label = '' }) {
  const client = getClient();
  if (!client) throw new Error('claude client unavailable');

  const stream = client.messages.stream({
    model: MODEL,
    max_tokens: maxTokens,
    thinking: { type: 'adaptive' },
    output_config: { effort: 'medium' },
    system: [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }],
    messages: [{ role: 'user', content: user }],
  });

  const msg = await stream.finalMessage();

  if (msg.stop_reason === 'refusal') {
    throw new Error('claude refused the request');
  }

  // Output ถูกตัดเพราะชนเพดาน max_tokens — ไม่ throw (คืน text เท่าที่ได้)
  // แต่ warn ให้เห็นใน log เผื่อยังตันอีกจะได้รู้ว่าต้องขยับ maxTokens
  if (msg.stop_reason === 'max_tokens') {
    console.warn(
      '[claude-ai] output truncated at max_tokens for label=' + (label || '?') +
      ' maxTokens=' + maxTokens +
      ' output_tokens=' + ((msg.usage && msg.usage.output_tokens) || '?')
    );
  }

  const text = (msg.content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('')
    .trim();

  if (!text) throw new Error('claude returned empty text');
  return { text, usage: msg.usage || null };
}

// ------------------------------------------------------------------
// Build the per-employee context block from the interview answers
// ------------------------------------------------------------------
function buildEmployeeContext(interview) {
  const e = interview.employee || {};
  const lines = [];
  lines.push(`วันที่จัดทำ (ใช้วันที่นี้เท่านั้น): ${todayStr()}`);
  lines.push('');
  lines.push('ข้อมูลพนักงาน:');
  lines.push(`- ชื่อ: ${e.name || '-'}`);
  lines.push(`- ตำแหน่ง: ${e.role || '-'}`);
  lines.push(`- ฝ่าย/แผนก: ${e.department || e.division_name || e.division_id || '-'}`);
  lines.push(`- ภาษาที่ใช้สัมภาษณ์: ${String(interview.lang || 'th').toUpperCase()}`);
  lines.push('');
  lines.push(`บทบาทโดยสรุป (จากคำตอบ): ${getAnswer(interview, 'warmup') || '(ไม่ระบุ)'}`);
  lines.push('');

  // Time content — prefer the new hourly schema, fall back to the legacy schema.
  const hourLines = [];
  for (let h = 0; h < 24; h++) {
    const v = getAnswer(interview, `hour_${h}`);
    if (v) hourLines.push(`- ${pad(h)}:00–${pad(h + 1)}:00 → ${v}`);
  }
  if (hourLines.length) {
    lines.push('ตารางงานรายชั่วโมง:');
    lines.push(...hourLines);
  } else {
    const legacy = [
      ['morning_first', '30 นาทีแรกของวัน'],
      ['morning_main', 'งานหลักช่วงสาย (09:30–12:00)'],
      ['morning_tools', 'เครื่องมือ/ระบบช่วงเช้า'],
      ['morning_people', 'ประสานงานช่วงเช้ากับ'],
      ['noon_break', 'พักเที่ยง'],
      ['afternoon_main', 'งานบ่าย (13:00–16:00)'],
      ['afternoon_reports', 'รายงานประจำวัน'],
      ['afternoon_deadline', 'Deadline รายวัน'],
      ['evening_closing', 'ก่อนเลิกงาน'],
    ];
    const legacyLines = legacy
      .map(([k, label]) => {
        const v = getAnswer(interview, k);
        return v ? `- ${label}: ${v}` : null;
      })
      .filter(Boolean);
    if (legacyLines.length) {
      lines.push('ตารางงานประจำวัน:');
      lines.push(...legacyLines);
    }
  }
  lines.push('');

  const tail = [
    ['weekly_tasks', 'งานรายสัปดาห์/รายเดือน'],
    ['pain_points', 'งานที่เสียเวลา/น่าเบื่อ/ทำซ้ำที่สุด'],
    ['bottlenecks', 'คอขวด — รออะไรจากคน/ระบบอื่น'],
    ['own_kpi', 'ตัวชี้วัดในมุมพนักงานเอง'],
    ['ai_wishlist', 'งานที่พนักงานอยากให้ AI ช่วย'],
  ];
  for (const [k, label] of tail) {
    const v = getAnswer(interview, k);
    if (v) lines.push(`${label}: ${v}`);
  }

  const divAns = (interview.answers || []).filter((a) => a.key.startsWith('div_'));
  if (divAns.length) {
    lines.push('');
    lines.push('ข้อมูลเฉพาะฝ่าย:');
    for (const a of divAns) lines.push(`- ${a.value}`);
  }

  if (interview.worklogSummary) {
    lines.push('');
    lines.push('— ข้อมูลจากบันทึกงานประจำวันจริง (สำคัญ: ใช้ประกอบการวิเคราะห์ โดยเฉพาะ KPI และ Optimization — งานที่ทำซ้ำบ่อยคือเป้าหมายการลดงาน/ใช้ AI) —');
    lines.push(interview.worklogSummary);
  }

  return lines.join('\n');
}

// ------------------------------------------------------------------
// 1) Per-employee analytical documents (JD / KPI / Optimization)
// ------------------------------------------------------------------
const SYS_DOCS = `คุณเป็นผู้เชี่ยวชาญด้านทรัพยากรบุคคล (HR) และที่ปรึกษาการจัดการองค์กรที่มีประสบการณ์สูง สำหรับองค์กรในประเทศไทย

หน้าที่: อ่าน "ข้อมูลการสัมภาษณ์การทำงานประจำวัน" ของพนักงาน 1 คน แล้วจัดทำเอกสาร 3 ฉบับเป็นภาษาไทย รูปแบบ Markdown ได้แก่
(1) Job Description — ใบกำหนดหน้าที่งานที่อิงจากงานจริงที่พนักงานทำ
(2) KPI — ตัวชี้วัดผลงานที่วัดได้จริง สอดคล้องกับหน้าที่
(3) Optimization — ข้อเสนอปรับปรุง workflow และการนำ AI/automation มาช่วย

กฎสำคัญ:
- ใช้เฉพาะข้อเท็จจริงที่ปรากฏในข้อมูลสัมภาษณ์เท่านั้น ห้ามแต่งตัวเลข ชื่อระบบ หรือรายละเอียดที่ไม่มีในข้อมูล หากข้อมูลไม่พอในหัวข้อใด ให้เขียนว่า "(ข้อมูลไม่เพียงพอ — ควรสอบถามเพิ่ม)"
- เขียนให้เป็นรูปธรรม อ้างถึงงาน/เครื่องมือ/ช่วงเวลาจริงที่พนักงานบอก ไม่ใช้คำกว้าง ๆ ลอย ๆ
- ภาษากระชับ มืออาชีพ เหมาะนำเสนอผู้บริหาร
- หากต้องระบุวันที่ ให้ใช้ "วันที่จัดทำ" ที่ให้ไว้ในข้อมูลเท่านั้น (รูปแบบ ค.ศ.) ห้ามเดาหรือแต่งวันที่เอง
- ห้ามใส่ข้อความนำ/ทักทาย/สรุปนอกเหนือจากเนื้อหาเอกสาร และห้ามครอบด้วย code fence

โครงสร้างของแต่ละเอกสาร:

[Job Description]
- ขึ้นต้นด้วย "# Job Description: <ชื่อพนักงาน>"
- ## ตำแหน่ง (พร้อมแผนก/ฝ่าย)
- ## สรุปบทบาท (Role Summary) 2–3 บรรทัด
- ## หน้าที่หลัก (Primary Responsibilities) — bullet
- ## หน้าที่รอง (Secondary Responsibilities) — bullet
- ## เครื่องมือ/ระบบที่ต้องใช้ — bullet
- ## การประสานงาน (ทำงานร่วมกับใคร/ฝ่ายใด) — bullet
- ## คุณสมบัติ/Competency ที่จำเป็น — bullet (สังเกตจากงานจริง)
- ## ตัวชี้วัดที่เกี่ยวข้อง (เชื่อมกับ KPI) — bullet สั้น ๆ

[KPI]
- ขึ้นต้นด้วย "# KPI: <ชื่อพนักงาน> (<ตำแหน่ง>)"
- กำหนด KPI 4–6 ตัว ที่อิงจากงานจริง แต่ละตัวต้องมี: ชื่อ KPI / สิ่งที่วัด / สูตรคำนวณ / เป้าหมาย (ตัวเลขสมเหตุสมผล) / ความถี่ในการวัด / น้ำหนัก (%)
- น้ำหนักรวมทุก KPI = 100%
- ปิดท้ายด้วย ## วิธีนำไปใช้ (Baseline → ตกลงเป้ากับหัวหน้า → ทบทวนรายไตรมาส)

[Optimization]
- ขึ้นต้นด้วย "# Optimization: <ชื่อพนักงาน> (<ตำแหน่ง>)"
- ## ปัญหา/คอขวดที่พบ — สรุปจากข้อมูล
- ## ข้อเสนอการปรับปรุง — แต่ละข้อระบุ: ปัญหา / ข้อเสนอเชิงรูปธรรม (ถ้าใช้ AI ให้เจาะจงว่าใช้กับงานไหน อย่างไร) / ผลกระทบ (impact: สูง/กลาง/ต่ำ) / ความเสี่ยง / ความยากง่ายในการทำ
- ## Quick Wins (ทำได้เร็ว) กับ ## ระยะยาว แยกกัน
- ## ประมาณการเวลาที่ประหยัดได้ (ระบุว่าเป็นการประมาณ ต้อง baseline ก่อนวัดจริง)

รูปแบบผลลัพธ์ — ตอบกลับเป็นข้อความเดียว แบ่งเป็น 3 ส่วนด้วยเครื่องหมายคั่นต่อไปนี้แบบเป๊ะ ๆ (ต้องมีครบทั้ง 3 เครื่องหมาย และห้ามมีข้อความอื่นนอกเหนือจากนี้):
===JOB_DESCRIPTION===
<เนื้อหา Markdown ของ Job Description>
===KPI===
<เนื้อหา Markdown ของ KPI>
===OPTIMIZATION===
<เนื้อหา Markdown ของ Optimization>`;

function splitDocs(text) {
  const re = /===JOB_DESCRIPTION===([\s\S]*?)===KPI===([\s\S]*?)===OPTIMIZATION===([\s\S]*)$/;
  const m = text.match(re);
  if (!m) return null;
  const jd = m[1].trim();
  const kpi = m[2].trim();
  const opt = m[3].trim();
  if (!jd || !kpi || !opt) return null;
  return { jd, kpi, opt };
}

async function generateDocuments(interview, opts = {}) {
  // Always start from the mock output: this gives us the 3 mechanical docs for
  // free AND a complete safe fallback for the 3 analytical docs.
  const docs = mock.generateDocuments(interview);

  if (!isEnabled()) return docs;

  try {
    const { text, usage } = await runClaude({
      system: SYS_DOCS,
      user: buildEmployeeContext(interview),
      // เอกสารรายคน 3 ฉบับใน 1 คำตอบ — เพิ่มจาก 8000 เป็น 12000 กันตัดกรณีคนงานละเอียด
      maxTokens: 12000,
      label: 'documents:' + ((interview.employee && interview.employee.name) || '?'),
    });
    // Report token usage/cost even if parsing later fails — the tokens were spent.
    if (usage && typeof opts.onUsage === 'function') {
      try { opts.onUsage(usageRecord(usage)); } catch (_) {}
    }
    const parsed = splitDocs(text);
    if (parsed) {
      docs['job-description.md'] = parsed.jd;
      docs['kpi.md'] = parsed.kpi;
      docs['optimization.md'] = parsed.opt;
    } else {
      console.error('[claude-ai] could not parse 3-section output — keeping mock JD/KPI/Optimization');
    }
  } catch (e) {
    console.error('[claude-ai] generateDocuments failed — keeping mock JD/KPI/Optimization: ' + e.message);
  }

  return docs;
}

// ------------------------------------------------------------------
// 2) Company-wide analysis report
// ------------------------------------------------------------------
const SYS_COMPANY = `คุณเป็นที่ปรึกษาด้านการจัดการและ Transformation อาวุโส กำลังจัดทำรายงานวิเคราะห์ภาพรวมองค์กรในประเทศไทย จากผลการสัมภาษณ์การทำงานประจำวันของพนักงานหลายคน

หน้าที่: สังเคราะห์ข้อมูลทั้งหมด แล้วเขียนรายงานภาษาไทย รูปแบบ Markdown 1 ฉบับ สำหรับนำเสนอผู้บริหารระดับสูง

กฎสำคัญ:
- วิเคราะห์ข้ามฝ่าย หาธีมปัญหาที่เกิดซ้ำหลายคน/หลายฝ่าย ไม่ใช่แค่ลิสต์รายคน
- ใช้ทั้ง "คำตอบสัมภาษณ์" และ "สรุปบันทึกงานจริง" ประกอบกัน — ถ้าบันทึกงานจริงชี้ว่างานซ้ำ/งานประจำกินเวลามาก ให้ยกเป็นหลักฐานสนับสนุนข้อเสนอ
- อิงจากข้อมูลจริงเท่านั้น ห้ามแต่งตัวเลขหรือข้อเท็จจริงที่ไม่มี
- จัดลำดับความสำคัญของข้อเสนอแบบ impact ปะทะ effort
- ภาษากระชับ ตรงประเด็น เหมาะนำเสนอผู้บริหาร
- ในส่วน "วันที่จัดทำ" ให้ใช้วันที่ที่ระบุไว้ในข้อมูลเท่านั้น (รูปแบบ ค.ศ.) ห้ามเดาหรือแต่งวันที่เอง
- ห้ามครอบผลลัพธ์ด้วย code fence และห้ามมีข้อความนำ/ทักทาย

โครงสร้างรายงาน:
- "# รายงานวิเคราะห์ภาพรวมองค์กร — Optimization"
- ## บทสรุปผู้บริหาร (Executive Summary) 3–5 บรรทัด
- ## ความครอบคลุมรายฝ่าย (จำนวนคนที่สัมภาษณ์ในแต่ละฝ่าย)
- ## ธีมปัญหา/คอขวดที่พบซ้ำ — จัดกลุ่มเป็นหัวข้อ พร้อมระบุว่าพบในฝ่ายใด/กี่คน
- ## โอกาสใช้ AI/Automation — จัดลำดับความสำคัญ (impact สูง→ต่ำ) แต่ละข้อบอกว่าช่วยงานอะไร กระทบใครบ้าง
- ## ข้อเสนอภาพรวม + Roadmap 3–6 เดือน (แบ่ง Quick Wins / ระยะกลาง / ระยะยาว)
- ## ความเสี่ยงและข้อควรระวัง`;

function buildCompanyContext(interviews, scope) {
  const lines = [];
  if (scope) {
    lines.push(`ขอบเขตของรายงานนี้: ${scope} — วิเคราะห์เฉพาะกลุ่มนี้เท่านั้น ไม่ใช่ทั้งบริษัท`);
    lines.push(`ให้หัวข้อ เนื้อหา และบทสรุปสะท้อน "${scope}" (แทนคำว่า "องค์กร/บริษัท" ด้วยชื่อกลุ่มนี้)`);
  }
  lines.push(`วันที่จัดทำรายงาน (ใช้วันที่นี้เท่านั้น): ${todayStr()}`);
  lines.push(`จำนวนพนักงานที่สัมภาษณ์เสร็จแล้ว: ${interviews.length} คน`);
  lines.push('');
  interviews.forEach((iv, i) => {
    const e = iv.employee || {};
    lines.push(
      `[${i + 1}] ${e.name || '-'} — ${e.role || '-'} (ฝ่าย: ${e.division_name || e.division_id || '-'})`
    );
    const role = getAnswer(iv, 'warmup');
    if (role) lines.push(`   บทบาท: ${trunc(role, 200)}`);
    const pain = getAnswer(iv, 'pain_points');
    if (pain) lines.push(`   ปัญหา/เสียเวลา: ${trunc(pain, 300)}`);
    const bot = getAnswer(iv, 'bottlenecks');
    if (bot) lines.push(`   คอขวด: ${trunc(bot, 300)}`);
    const wish = getAnswer(iv, 'ai_wishlist');
    if (wish) lines.push(`   อยากให้ AI ช่วย: ${trunc(wish, 300)}`);
    const kpi = getAnswer(iv, 'own_kpi');
    if (kpi) lines.push(`   ตัวชี้วัดในมุมตัวเอง: ${trunc(kpi, 200)}`);
    if (iv.worklogSummary) lines.push(`   [บันทึกงานจริง] ${trunc(String(iv.worklogSummary).replace(/\s+/g, ' '), 500)}`);
    lines.push('');
  });
  return lines.join('\n');
}

async function analyzeCompany(interviews, opts = {}) {
  const list = interviews || [];
  if (!list.length) return mock.analyzeCompany(list);
  if (!isEnabled()) return mock.analyzeCompany(list);

  try {
    const { text, usage } = await runClaude({
      system: SYS_COMPANY,
      user: buildCompanyContext(list, opts.scope),
      // รายงานภาพรวมองค์กร: คนเยอะ (เช่น 27 คน) รายงานยาวเกิน 8000 เลยถูกตัดกลางคัน
      // ขยับเป็น 20000 ให้พอ + เผื่อ thinking(adaptive) กินงบโทเคนร่วมด้วย
      maxTokens: 20000,
      label: (opts.scope ? 'scope:' + opts.scope + ' — ' : 'company:') + list.length + ' คน',
    });
    if (usage && typeof opts.onUsage === 'function') {
      try { opts.onUsage(usageRecord(usage)); } catch (_) {}
    }
    return text;
  } catch (e) {
    console.error('[claude-ai] analyzeCompany failed — using mock report: ' + e.message);
    return mock.analyzeCompany(list);
  }
}

// ------------------------------------------------------------------
// 3) รายงานรายคน + รายงานภาพรวม (v1.17) — server สร้าง context ให้ครบแล้ว
//    ทุกฟังก์ชัน "โยน error" ถ้าไม่สำเร็จ → server มี fallback เชิงกลไกเสมอ
// ------------------------------------------------------------------
const SYS_SCHEDULE = `คุณเป็นผู้เชี่ยวชาญด้าน HR และการออกแบบงาน (Workflow) ในองค์กรไทย
หน้าที่: จาก "บันทึกงานจริงรายวัน" (สรุปแยกตามวันในสัปดาห์) และ "ข้อมูลสัมภาษณ์" ของพนักงาน 1 คน ให้สรุปเป็น "ตารางงาน" ที่ใช้ตั้งงานประจำได้จริง

รูปแบบคำตอบ: ตอบเป็นบรรทัดตารางเท่านั้น บรรทัดละ 1 งาน คั่นช่องด้วยเครื่องหมาย | จำนวน 5 ช่องตามลำดับ
ช่วง | เวลา/ช่วงในวัน | งาน | เป้าหมาย/ผลที่คาดหวัง | หมายเหตุ

ตารางมี 3 ส่วน เรียงตามนี้:
1) "ทุกวันทำงาน" = ไทม์ไลน์ 1 วันทำงานปกติ ว่าแต่ละช่วงเวลาต้องทำอะไร — ไล่ตั้งแต่เวลาเข้างานจนเลิกงานต่อเนื่องไม่ขาด (เช่น 08:00–09:00, 09:00–12:00, 12:00–13:00 พักกลางวัน, 13:00–15:00 …) ช่วงละ 1 งานหลัก (ถ้าทำสลับกันจริงให้เขียน "งาน A / งาน B") · แถวพักให้เขียนงานว่า "พักกลางวัน" และหมายเหตุว่า "พัก"
2) งานเฉพาะบางวัน = ใช้ชื่อวัน (จันทร์ … อาทิตย์) เฉพาะงานที่ทำประจำ "เฉพาะวันนั้น" (เช่น ประชุมทุกศุกร์) · ถ้าวันเสาร์/อาทิตย์ หรือวันที่เข้ากะ มีตารางต่างจากวันปกติมาก ให้ใส่ไทม์ไลน์ของวันนั้นด้วยชื่อวัน
3) งานตามรอบ = รายสัปดาห์ / รายเดือน / รายไตรมาส / รายปี อย่างละ 0–4 แถว (เวลา = เมื่อไหร่ เช่น สิ้นเดือน ต้นไตรมาส)

กฎ:
- "ช่วง" ต้องเป็นคำใดคำหนึ่งเท่านั้น: ทุกวันทำงาน, จันทร์, อังคาร, พุธ, พฤหัสบดี, ศุกร์, เสาร์, อาทิตย์, รายสัปดาห์, รายเดือน, รายไตรมาส, รายปี
- ห้ามใส่งานที่ทำครั้งเดียว/นาน ๆ ครั้ง (เช่น พบเพียง 1–2 วันจากหลายสิบวัน) · รวมงานชื่อคล้ายกันเป็นงานเดียว เขียนชื่องานให้กระชับ
- "เป้าหมาย/ผลที่คาดหวัง" สั้น ๆ เป็นรูปธรรม (เช่น "ปิดเคสภายในวัน", "แบบเสร็จตามกำหนด")
- "หมายเหตุ" บอกความถี่จากบันทึกจริง (เช่น "ทำ 8/10 วัน", "ทุกศุกร์") หรือ "อนุมาน" ถ้าคาดจากลักษณะงาน/คำสัมภาษณ์ (โดยเฉพาะรายไตรมาส/รายปี เพราะข้อมูลมีแค่ ~3 เดือน)
- ห้ามแต่งงานที่ไม่มีเค้าในข้อมูล · ห้ามใช้เครื่องหมาย | ในเนื้อหา · ห้ามมีหัวตาราง ข้อความนำ หรือ code fence`;

const SYS_SCOPE = `คุณเป็นที่ปรึกษาด้านการจัดการและ Transformation อาวุโส ในองค์กรไทย
หน้าที่: วิเคราะห์ "ทิศทางที่กลุ่มนี้ควรเดิน" (บริษัท/ฝ่าย/แผนก) จากข้อมูลงานจริงของพนักงานทุกคนในกลุ่ม — ไม่ใช่การนำข้อมูลมาเรียงโชว์ แต่สังเคราะห์เป็นข้อสรุปและข้อเสนอที่ผู้บริหารนำไปทำต่อได้

กฎ:
- สังเคราะห์ข้ามคน หาธีมร่วม อ้างตัวเลขภาระงานจริงที่ให้มาเป็นหลักฐาน · ห้ามแต่งตัวเลข/ข้อเท็จจริงที่ไม่มี
- ข้อเสนอเรียงตามผลกระทบ (สูง→ต่ำ) และบอกว่าทำอย่างไร ใครรับผิดชอบโดยประมาณ
- ภาษากระชับ ใช้บุลเล็ตได้ · ห้ามครอบด้วย code fence · ห้ามข้อความนำ/ทักทาย
- ใช้หัวข้อ ## ตามนี้ "เป๊ะ" ครบ 10 หัวข้อ เรียงตามลำดับ ห้ามเพิ่ม/ลด:
## ทิศทางที่ควรเป็น
## จุดแข็งที่ควรต่อยอด
## ปัญหา/คอขวดหลัก
## โอกาสพัฒนา & การนำ AI มาช่วย
## Roadmap 3–6 เดือน
## ความเสี่ยง/ข้อควรระวัง
## ภาระงาน & กำลังคน
## ทักษะที่ขาด & แผนอบรม
## งานที่ควรลด/รวม/โอน
## สิ่งที่ต้องทำใน 30 วันแรก`;

const SYS_POSITION = `คุณเป็นผู้เชี่ยวชาญด้านการออกแบบตำแหน่งงานและอัตรากำลัง (Job Design & Workforce Planning) ในองค์กรไทย
หน้าที่: วิเคราะห์ "ตำแหน่งงาน" 1 ตำแหน่ง จากข้อมูลงานจริงของคนที่อยู่ในตำแหน่งนี้ (ระบุเป็น คนที่ 1, คนที่ 2 ... ไม่ใช่ชื่อจริง) แล้วแนะนำว่าตำแหน่งนี้ควรมีหน้าที่อะไร ควรใช้กี่คน และตารางงานควรเป็นอย่างไร

กฎ:
- ห้ามอ้างชื่อบุคคล ให้พูดถึง "ตำแหน่ง" และใช้ คนที่ 1/คนที่ 2 เมื่อจำเป็น
- จำนวนคนที่แนะนำต้องอิงภาระงานจริงที่ให้มา (ชั่วโมงที่บันทึก ความครบ งานต่อชั่วโมง วันขาดบันทึก) และค่าแนะนำเบื้องต้นจากสูตร — ถ้างานเยอะเกินกำลังให้แนะนำเพิ่มคน ถ้าน้อยให้แนะนำรวม/รับงานเพิ่ม · ถ้าข้อมูลบันทึกงานไม่พอ ให้บอกตรง ๆ
- ห้ามแต่งตัวเลข/ข้อเท็จจริงที่ไม่มี · ภาษากระชับ ใช้บุลเล็ต · ห้าม code fence · ห้ามข้อความนำ
- ใช้หัวข้อ ## ตามนี้ "เป๊ะ" ครบ 7 หัวข้อ เรียงตามลำดับ:
## กำลังคนที่แนะนำ
(บรรทัดแรกต้องเป็น "จำนวน: <ตัวเลข> คน" แล้วตามด้วยเหตุผล 2–4 บรรทัด)
## หน้าที่ของตำแหน่งนี้
## เครื่องมือ/ทักษะที่ต้องมี
## สิ่งที่ควรทำ / ปรับปรุง
## KPI ที่ควรวัด
## ปัญหา/คอขวดที่ต้องจัดการ
## ตารางงานที่แนะนำ
(ตอบเป็นบรรทัดตาราง บรรทัดละ 1 งาน คั่นด้วย | 5 ช่อง: ช่วง | คนที่ | เวลา/ช่วงในวัน | งาน | เป้าหมาย
 "ช่วง" ใช้: ทุกวันทำงาน จันทร์ อังคาร พุธ พฤหัสบดี ศุกร์ เสาร์ อาทิตย์ รายสัปดาห์ รายเดือน รายไตรมาส รายปี
 - "ทุกวันทำงาน" = ไทม์ไลน์ 1 วันของแต่ละคน ไล่ตั้งแต่เข้างานจนเลิกงานต่อเนื่อง (ช่วงเวลา HH:MM–HH:MM) ช่วงละ 1 งาน · ให้ทุกคนใช้ขอบช่วงเวลาเดียวกันเท่าที่ทำได้ · แถวพักเขียนงานว่า "พักกลางวัน"
 - ชื่อวัน = เฉพาะงานที่ทำประจำเฉพาะวันนั้น · รายสัปดาห์/เดือน/ไตรมาส/ปี = งานตามรอบ
 - "คนที่" ใส่ตัวเลข 1..N ตามจำนวนที่แนะนำ หรือ "ทุกคน" · ถ้าแนะนำ 1 คน ให้ใส่ 1 ทุกบรรทัด · ห้ามใส่งานที่ทำครั้งเดียว · ห้ามใช้ | ในเนื้อหา · ห้ามมีหัวตาราง)`;

async function runReportText(system, user, opts, maxTokens, kind) {
  const { text, usage } = await runClaude({ system, user, maxTokens, label: kind + ':' + (opts.label || '') });
  if (usage && typeof opts.onUsage === 'function') { try { opts.onUsage(usageRecord(usage)); } catch (_) {} }
  return text;
}
// ตารางงานรายคน → ข้อความบรรทัดตาราง (server เป็นผู้ parse)
function inferSchedule(contextText, opts = {}) { return runReportText(SYS_SCHEDULE, contextText, opts, 6000, 'schedule'); }
// บทวิเคราะห์ทิศทาง บริษัท/ฝ่าย/แผนก → markdown 10 หัวข้อ
function analyzeScope(contextText, opts = {}) { return runReportText(SYS_SCOPE, contextText, opts, 16000, 'scope'); }
// วิเคราะห์ + แนะนำตำแหน่ง → markdown 7 หัวข้อ (ไม่อิงชื่อคน)
function analyzePosition(contextText, opts = {}) { return runReportText(SYS_POSITION, contextText, opts, 12000, 'position'); }

module.exports = {
  isEnabled,
  generateDocuments,
  analyzeCompany,
  inferSchedule,
  analyzeScope,
  analyzePosition,
  PRICING,
  USD_TO_THB,
  priceFor,
  // re-export the mock-only helpers so callers can use one module if they want
  getNextQuestion: mock.getNextQuestion,
  shouldProbe: mock.shouldProbe,
  listSchedules: mock.listSchedules,
  buildScript: mock.buildScript,
  SCHEDULES: mock.SCHEDULES,
  DIVISION_QUESTIONS: mock.DIVISION_QUESTIONS,
  questionsForDivision: mock.questionsForDivision,
  MODEL,
};
